<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans [
		<!ELEMENT beans (bean)*>
		<!ATTLIST beans
				xmlns CDATA #REQUIRED
				xmlns:xsi CDATA #REQUIRED
				xmlns:context CDATA #REQUIRED
				xmlns:aop CDATA #REQUIRED
				xmlns:tx CDATA #REQUIRED
				xsi:schemaLocation CDATA #REQUIRED
				default-lazy-init CDATA #REQUIRED>
		<!ELEMENT bean (property)*>
		<!ATTLIST bean
				class CDATA #REQUIRED
				destroy-method CDATA #IMPLIED
				id CDATA #IMPLIED>
		<!ELEMENT property (bean)*>
		<!ATTLIST property
				name CDATA #REQUIRED
				ref CDATA #IMPLIED
				value CDATA #IMPLIED>
		]>
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	   xmlns:aop="http://www.springframework.org/schema/aop" xmlns:tx="http://www.springframework.org/schema/tx"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
				http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.0.xsd
				http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-4.0.xsd
				http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-4.0.xsd"
	   default-lazy-init="false">

	<!-- fixedAddress -->
	<!--
	<bean id="fixedAddressProvider" class="cn.slimsmart.thrift.rpc.zookeeper.FixedAddressProvider">
		 <property name="service" value="cn.slimsmart.thrift.rpc.demo.EchoSerivce" />
         <property name="serverAddress" value="192.168.36.215:9001:1,192.168.36.215:9002:2,192.168.36.215:9003:3" />
	</bean>
    <bean id="echoSerivce" class="cn.slimsmart.thrift.rpc.ThriftServiceClientProxyFactory">
        <property name="maxActive" value="5" />
        <property name="idleTime" value="10000" />
        <property name="serverAddressProvider" ref="fixedAddressProvider" />
    </bean>
   -->
	<!-- zookeeper   -->
	<bean id="thriftZookeeper" class="zookeeper.impl.ZookeeperFactory"
		  destroy-method="close">
		<property name="zkHosts"
				  value="127.0.0.1:2181" />
		<property name="namespace" value="sgcc" />
		<property name="connectionTimeout" value="3000" />
		<property name="sessionTimeout" value="3000" />
		<property name="singleton" value="true" />
	</bean>
	<bean id="clientSerivce" class="rpcClient.ThriftServiceClientProxyFactory" destroy-method="close">
		<property name="maxActive" value="5" />
		<property name="idleTime" value="1800000" />
		<property name="serverAddressProvider">
			<bean class="zookeeper.impl.ThriftServerAddressProviderZookeeper">
				<property name="service" value="sgepri.sgcc.demo.Account" />
				<property name="version" value="1.0.0" />
				<property name="zkClient" ref="thriftZookeeper" />
			</bean>
		</property>
	</bean>
</beans>